# Generated by Django 3.0.1 on 2020-04-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urltable',
            name='type',
            field=models.CharField(default='link', max_length=10),
        ),
    ]
