# Generated by Django 3.0.1 on 2020-04-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0002_urltable_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subdomainlist',
            name='scanid',
        ),
        migrations.AlterField(
            model_name='urltable',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
