# Generated by Django 3.0.1 on 2020-04-14 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0003_auto_20200410_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scantime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='urltable',
            name='scanid',
            field=models.IntegerField(default=0),
        ),
    ]
