# Generated by Django 3.0.7 on 2020-10-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0006_auto_20200804_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomainlist',
            name='banner',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='subdomainlist',
            name='is_emergency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subdomainlist',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subdomainlist',
            name='title',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
    ]
