# Generated by Django 3.0.7 on 2022-08-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0007_auto_20201010_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdomainlist',
            name='lastscan',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
