# Generated by Django 3.0.7 on 2022-08-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20220329_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSubdomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('subdomain', models.CharField(max_length=200)),
                ('title', models.CharField(default='', max_length=1000, null=True)),
                ('banner', models.CharField(default='', max_length=1000, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
