# Generated by Django 3.0.7 on 2022-08-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_projectsubdomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsubdomain',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
