# Generated by Django 3.0.7 on 2022-09-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_projectsubdomain_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='iphone',
            field=models.CharField(max_length=20),
        ),
    ]
