# Generated by Django 3.0.7 on 2022-09-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20220920_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectannouncement',
            name='link',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
