# Generated by Django 3.0.7 on 2022-03-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScaVuls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('vultype_id', models.IntegerField(max_length=10)),
                ('severity', models.IntegerField(default=0, max_length=2)),
                ('link', models.CharField(max_length=200, null=True)),
                ('details', models.CharField(default=None, max_length=5000, null=True)),
                ('affected_version', models.CharField(max_length=500, null=True)),
                ('create_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
