# Generated by Django 3.0.7 on 2022-03-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scavuls',
            name='severity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scavuls',
            name='vultype_id',
            field=models.IntegerField(),
        ),
    ]
