# Generated by Django 3.0.1 on 2020-04-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scantask',
            name='last_scan_time',
            field=models.DateTimeField(default=None),
        ),
    ]
