# Generated by Django 3.0.1 on 2020-04-07 09:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_scantask_last_scan_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scantask',
            name='last_scan_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 7, 9, 56, 27, 101552, tzinfo=utc)),
        ),
    ]
