# Generated by Django 3.0.1 on 2020-04-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20200407_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scantask',
            name='last_scan_time',
            field=models.DateTimeField(),
        ),
    ]
