# Generated by Django 3.0.7 on 2020-08-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20200423_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scantask',
            name='cookies',
            field=models.CharField(default=None, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='scantask',
            name='target',
            field=models.CharField(max_length=5000),
        ),
    ]
