# Generated by Django 3.0.7 on 2020-10-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20201010_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginpagelist',
            name='title',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
