# Generated by Django 3.0.7 on 2022-08-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_loginpagelist_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scantask',
            name='last_scan_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
